<a href="https://colab.research.google.com/github/pabloperfer/CUDAexercises/blob/main/Multiply2DMatricesGPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [136]:
from numba.cuda.cudadrv.devices import reset
import numpy as np
from numba import cuda

@cuda.jit
def mm(a,b,c):
  row, column = cuda.grid(2)
  sum = 0
  
  for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
          sum = sum + a[i][k]*b[k][j]
        c[i][j] = sum
        sum=0


In [139]:
a=np.arange(16).reshape(4,4).astype(np.int32)
b=np.arange(16).reshape(4,4).astype(np.int32)
c=np.zeros_like(a)

d_a = cuda.to_device(a)
d_b = cuda.to_device(b)
d_c = cuda.to_device(c)

grid=(2,2)
block=(2,2)
mm[grid, block](d_a, d_b, d_c)


In [140]:
from numpy import testing
solution= a@b
output=d_c.copy_to_host()
print (output)

testing.assert_array_equal(output, solution)

[[ 56  62  68  74]
 [152 174 196 218]
 [248 286 324 362]
 [344 398 452 506]]
